### ISSUE TITLE
Missing handling for resource pool APIs

### ISSUE THREAD

**Issue by Prabhjot-Sethi** [maas/gomaasclient#25]
Hi we are using maas controller in one of our projects and we don't see the availablility of resource pool apis in this library.

Please let us know if there is work happening in this direction. Otherwise we can contribute.

**Comment by skatsaounis** [comment]
Hi @Prabhjot-Sethi 

Thank you for opening this issue. Since it was an easy addition, I just created a PR which adds the resource pool  management to the client. Please give us some time to review and soon it will land to master branch.
