### ISSUE TITLE
Providing filter values to machines endpoint

### ISSUE THREAD

**Issue by matthewconolly-lambda** [maas/gomaasclient#67]
Hi, when using the `Machines` `Get()` to fetch information about all the machines it can take significant time to return all the machines.

My use case is that I want to search for a machine that has a particular characteristic, like a hostname or ip/mac address, so that I then know MAAS's system id for the machine.

Is it possible to expose the query options from `/MAAS/api/2.0/machines/` such that we can do things like ask for machines that have a particular hostname or ip/mac?

Currently I'm using a `Machines` `Get()` and then finding the right machine by client-side filtering, then using the `Machine` api for actual operations, but that is heavy load on our deployment.

**Comment by matthewconolly-lambda** [comment]
If it helps, I was able to use the deprecated `APIClient`
```
apiclient, _ := gomaasclient.GetAPIClient(url, key, apiVersion)
machineAPI := apiclient.GetSubObject("machines")

machines := make([]entity.Machine, 0)

_ := machineAPI.Get("", url.Values{"hostname": []string{hostname}}, func(data []byte) error {
    return json.Unmarshal(data, &machines)
})

fmt.Println(machines)
```

**Comment by skatsaounis** [comment]
Hi @matthewconolly-lambda

Thank you for opening this issue. Based on the [API docs](https://maas.io/docs/api) and your findings, the machines endpoint should accept a couple of parameters. As the current implementation of gomaasclient is not accepting any, I am considering this issue a bug.
